package pro.modelo.entidad;
// Generated 26/05/2015 09:40:05 AM by Hibernate Tools 4.3.1



/**
 * Boleto generated by hbm2java
 */
public class Boleto  implements java.io.Serializable {


     private String idBoleto;
     private Pasajero pasajero;
     private Viaje viaje;
     private String precioPagar;
     private String total;

    public Boleto() {
    }

	
    public Boleto(String idBoleto, Pasajero pasajero, Viaje viaje) {
        this.idBoleto = idBoleto;
        this.pasajero = pasajero;
        this.viaje = viaje;
    }
    public Boleto(String idBoleto, Pasajero pasajero, Viaje viaje, String precioPagar, String total) {
       this.idBoleto = idBoleto;
       this.pasajero = pasajero;
       this.viaje = viaje;
       this.precioPagar = precioPagar;
       this.total = total;
    }
   
    public String getIdBoleto() {
        return this.idBoleto;
    }
    
    public void setIdBoleto(String idBoleto) {
        this.idBoleto = idBoleto;
    }
    public Pasajero getPasajero() {
        return this.pasajero;
    }
    
    public void setPasajero(Pasajero pasajero) {
        this.pasajero = pasajero;
    }
    public Viaje getViaje() {
        return this.viaje;
    }
    
    public void setViaje(Viaje viaje) {
        this.viaje = viaje;
    }
    public String getPrecioPagar() {
        return this.precioPagar;
    }
    
    public void setPrecioPagar(String precioPagar) {
        this.precioPagar = precioPagar;
    }
    public String getTotal() {
        return this.total;
    }
    
    public void setTotal(String total) {
        this.total = total;
    }




}


