package pro.modelo.entidad;
// Generated 26/05/2015 09:40:05 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ciudad generated by hbm2java
 */
public class Ciudad  implements java.io.Serializable {


     private String idCiudad;
     private Ciudad ciudad;
     private String nombre;
     private Set ciudads = new HashSet(0);
     private Set viajesForIdCiudaddestino = new HashSet(0);
     private Set viajesForIdCiudad = new HashSet(0);

    public Ciudad() {
    }

	
    public Ciudad(String idCiudad, Ciudad ciudad) {
        this.idCiudad = idCiudad;
        this.ciudad = ciudad;
    }
    public Ciudad(String idCiudad, Ciudad ciudad, String nombre, Set ciudads, Set viajesForIdCiudaddestino, Set viajesForIdCiudad) {
       this.idCiudad = idCiudad;
       this.ciudad = ciudad;
       this.nombre = nombre;
       this.ciudads = ciudads;
       this.viajesForIdCiudaddestino = viajesForIdCiudaddestino;
       this.viajesForIdCiudad = viajesForIdCiudad;
    }
   
    public String getIdCiudad() {
        return this.idCiudad;
    }
    
    public void setIdCiudad(String idCiudad) {
        this.idCiudad = idCiudad;
    }
    public Ciudad getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(Ciudad ciudad) {
        this.ciudad = ciudad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getCiudads() {
        return this.ciudads;
    }
    
    public void setCiudads(Set ciudads) {
        this.ciudads = ciudads;
    }
    public Set getViajesForIdCiudaddestino() {
        return this.viajesForIdCiudaddestino;
    }
    
    public void setViajesForIdCiudaddestino(Set viajesForIdCiudaddestino) {
        this.viajesForIdCiudaddestino = viajesForIdCiudaddestino;
    }
    public Set getViajesForIdCiudad() {
        return this.viajesForIdCiudad;
    }
    
    public void setViajesForIdCiudad(Set viajesForIdCiudad) {
        this.viajesForIdCiudad = viajesForIdCiudad;
    }




}


