package pro.modelo.entidad;
// Generated 26/05/2015 09:40:05 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Color generated by hbm2java
 */
public class Color  implements java.io.Serializable {


     private String idColor;
     private String nombre;
     private Set vehiculos = new HashSet(0);

    public Color() {
    }

	
    public Color(String idColor) {
        this.idColor = idColor;
    }
    public Color(String idColor, String nombre, Set vehiculos) {
       this.idColor = idColor;
       this.nombre = nombre;
       this.vehiculos = vehiculos;
    }
   
    public String getIdColor() {
        return this.idColor;
    }
    
    public void setIdColor(String idColor) {
        this.idColor = idColor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getVehiculos() {
        return this.vehiculos;
    }
    
    public void setVehiculos(Set vehiculos) {
        this.vehiculos = vehiculos;
    }




}


