package pro.modelo.entidad;
// Generated 26/05/2015 09:40:05 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Marca generated by hbm2java
 */
public class Marca  implements java.io.Serializable {


     private String idMarca;
     private String nombre;
     private Set vehiculos = new HashSet(0);

    public Marca() {
    }

	
    public Marca(String idMarca) {
        this.idMarca = idMarca;
    }
    public Marca(String idMarca, String nombre, Set vehiculos) {
       this.idMarca = idMarca;
       this.nombre = nombre;
       this.vehiculos = vehiculos;
    }
   
    public String getIdMarca() {
        return this.idMarca;
    }
    
    public void setIdMarca(String idMarca) {
        this.idMarca = idMarca;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getVehiculos() {
        return this.vehiculos;
    }
    
    public void setVehiculos(Set vehiculos) {
        this.vehiculos = vehiculos;
    }




}


