package pro.modelo.entidad;
// Generated 26/05/2015 09:40:05 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Modelo generated by hbm2java
 */
public class Modelo  implements java.io.Serializable {


     private String idModelo;
     private String nombre;
     private Set vehiculos = new HashSet(0);

    public Modelo() {
    }

	
    public Modelo(String idModelo) {
        this.idModelo = idModelo;
    }
    public Modelo(String idModelo, String nombre, Set vehiculos) {
       this.idModelo = idModelo;
       this.nombre = nombre;
       this.vehiculos = vehiculos;
    }
   
    public String getIdModelo() {
        return this.idModelo;
    }
    
    public void setIdModelo(String idModelo) {
        this.idModelo = idModelo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getVehiculos() {
        return this.vehiculos;
    }
    
    public void setVehiculos(Set vehiculos) {
        this.vehiculos = vehiculos;
    }




}


