package pro.modelo.entidad;
// Generated 26/05/2015 09:40:05 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pagos generated by hbm2java
 */
public class Pagos  implements java.io.Serializable {


     private String idPagos;
     private String descripcion;
     private String cantidad;
     private Date fecha;
     private String total;
     private Set viajes = new HashSet(0);

    public Pagos() {
    }

	
    public Pagos(String idPagos) {
        this.idPagos = idPagos;
    }
    public Pagos(String idPagos, String descripcion, String cantidad, Date fecha, String total, Set viajes) {
       this.idPagos = idPagos;
       this.descripcion = descripcion;
       this.cantidad = cantidad;
       this.fecha = fecha;
       this.total = total;
       this.viajes = viajes;
    }
   
    public String getIdPagos() {
        return this.idPagos;
    }
    
    public void setIdPagos(String idPagos) {
        this.idPagos = idPagos;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(String cantidad) {
        this.cantidad = cantidad;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getTotal() {
        return this.total;
    }
    
    public void setTotal(String total) {
        this.total = total;
    }
    public Set getViajes() {
        return this.viajes;
    }
    
    public void setViajes(Set viajes) {
        this.viajes = viajes;
    }




}


