package pro.modelo.entidad;
// Generated 26/05/2015 09:40:05 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Personal generated by hbm2java
 */
public class Personal  implements java.io.Serializable {


     private String idPersona;
     private Tipo tipo;
     private String nroLicencia;
     private Set viajes = new HashSet(0);

    public Personal() {
    }

	
    public Personal(String idPersona, Tipo tipo) {
        this.idPersona = idPersona;
        this.tipo = tipo;
    }
    public Personal(String idPersona, Tipo tipo, String nroLicencia, Set viajes) {
       this.idPersona = idPersona;
       this.tipo = tipo;
       this.nroLicencia = nroLicencia;
       this.viajes = viajes;
    }
   
    public String getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(String idPersona) {
        this.idPersona = idPersona;
    }
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }
    public String getNroLicencia() {
        return this.nroLicencia;
    }
    
    public void setNroLicencia(String nroLicencia) {
        this.nroLicencia = nroLicencia;
    }
    public Set getViajes() {
        return this.viajes;
    }
    
    public void setViajes(Set viajes) {
        this.viajes = viajes;
    }




}


