package pro.modelo.entidad;
// Generated 26/05/2015 09:40:05 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipo generated by hbm2java
 */
public class Tipo  implements java.io.Serializable {


     private String idTipo;
     private String nombre;
     private Set personals = new HashSet(0);

    public Tipo() {
    }

	
    public Tipo(String idTipo) {
        this.idTipo = idTipo;
    }
    public Tipo(String idTipo, String nombre, Set personals) {
       this.idTipo = idTipo;
       this.nombre = nombre;
       this.personals = personals;
    }
   
    public String getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(String idTipo) {
        this.idTipo = idTipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getPersonals() {
        return this.personals;
    }
    
    public void setPersonals(Set personals) {
        this.personals = personals;
    }




}


