package pro.modelo.entidad;
// Generated 26/05/2015 09:40:05 AM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String idPersona;
     private String login;
     private String password;

    public Usuario() {
    }

	
    public Usuario(String idPersona) {
        this.idPersona = idPersona;
    }
    public Usuario(String idPersona, String login, String password) {
       this.idPersona = idPersona;
       this.login = login;
       this.password = password;
    }
   
    public String getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(String idPersona) {
        this.idPersona = idPersona;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


