package pro.modelo.entidad;
// Generated 26/05/2015 09:40:05 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vehiculo generated by hbm2java
 */
public class Vehiculo  implements java.io.Serializable {


     private String idVehiculo;
     private Persona persona;
     private Marca marca;
     private Color color;
     private Modelo modelo;
     private String nroPlaca;
     private Set viajes = new HashSet(0);

    public Vehiculo() {
    }

	
    public Vehiculo(String idVehiculo, Persona persona, Marca marca, Color color, Modelo modelo) {
        this.idVehiculo = idVehiculo;
        this.persona = persona;
        this.marca = marca;
        this.color = color;
        this.modelo = modelo;
    }
    public Vehiculo(String idVehiculo, Persona persona, Marca marca, Color color, Modelo modelo, String nroPlaca, Set viajes) {
       this.idVehiculo = idVehiculo;
       this.persona = persona;
       this.marca = marca;
       this.color = color;
       this.modelo = modelo;
       this.nroPlaca = nroPlaca;
       this.viajes = viajes;
    }
   
    public String getIdVehiculo() {
        return this.idVehiculo;
    }
    
    public void setIdVehiculo(String idVehiculo) {
        this.idVehiculo = idVehiculo;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    public Color getColor() {
        return this.color;
    }
    
    public void setColor(Color color) {
        this.color = color;
    }
    public Modelo getModelo() {
        return this.modelo;
    }
    
    public void setModelo(Modelo modelo) {
        this.modelo = modelo;
    }
    public String getNroPlaca() {
        return this.nroPlaca;
    }
    
    public void setNroPlaca(String nroPlaca) {
        this.nroPlaca = nroPlaca;
    }
    public Set getViajes() {
        return this.viajes;
    }
    
    public void setViajes(Set viajes) {
        this.viajes = viajes;
    }




}


