package pro.modelo.entidad;
// Generated 26/05/2015 09:40:05 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Viaje generated by hbm2java
 */
public class Viaje  implements java.io.Serializable {


     private String idViaje;
     private Vehiculo vehiculo;
     private Ciudad ciudadByIdCiudaddestino;
     private Ciudad ciudadByIdCiudad;
     private Personal personal;
     private Pagos pagos;
     private String fechaViaje;
     private String horaViaje;
     private String total;
     private Set boletos = new HashSet(0);

    public Viaje() {
    }

	
    public Viaje(String idViaje, Vehiculo vehiculo, Ciudad ciudadByIdCiudaddestino, Ciudad ciudadByIdCiudad, Personal personal, Pagos pagos) {
        this.idViaje = idViaje;
        this.vehiculo = vehiculo;
        this.ciudadByIdCiudaddestino = ciudadByIdCiudaddestino;
        this.ciudadByIdCiudad = ciudadByIdCiudad;
        this.personal = personal;
        this.pagos = pagos;
    }
    public Viaje(String idViaje, Vehiculo vehiculo, Ciudad ciudadByIdCiudaddestino, Ciudad ciudadByIdCiudad, Personal personal, Pagos pagos, String fechaViaje, String horaViaje, String total, Set boletos) {
       this.idViaje = idViaje;
       this.vehiculo = vehiculo;
       this.ciudadByIdCiudaddestino = ciudadByIdCiudaddestino;
       this.ciudadByIdCiudad = ciudadByIdCiudad;
       this.personal = personal;
       this.pagos = pagos;
       this.fechaViaje = fechaViaje;
       this.horaViaje = horaViaje;
       this.total = total;
       this.boletos = boletos;
    }
   
    public String getIdViaje() {
        return this.idViaje;
    }
    
    public void setIdViaje(String idViaje) {
        this.idViaje = idViaje;
    }
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }
    public Ciudad getCiudadByIdCiudaddestino() {
        return this.ciudadByIdCiudaddestino;
    }
    
    public void setCiudadByIdCiudaddestino(Ciudad ciudadByIdCiudaddestino) {
        this.ciudadByIdCiudaddestino = ciudadByIdCiudaddestino;
    }
    public Ciudad getCiudadByIdCiudad() {
        return this.ciudadByIdCiudad;
    }
    
    public void setCiudadByIdCiudad(Ciudad ciudadByIdCiudad) {
        this.ciudadByIdCiudad = ciudadByIdCiudad;
    }
    public Personal getPersonal() {
        return this.personal;
    }
    
    public void setPersonal(Personal personal) {
        this.personal = personal;
    }
    public Pagos getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Pagos pagos) {
        this.pagos = pagos;
    }
    public String getFechaViaje() {
        return this.fechaViaje;
    }
    
    public void setFechaViaje(String fechaViaje) {
        this.fechaViaje = fechaViaje;
    }
    public String getHoraViaje() {
        return this.horaViaje;
    }
    
    public void setHoraViaje(String horaViaje) {
        this.horaViaje = horaViaje;
    }
    public String getTotal() {
        return this.total;
    }
    
    public void setTotal(String total) {
        this.total = total;
    }
    public Set getBoletos() {
        return this.boletos;
    }
    
    public void setBoletos(Set boletos) {
        this.boletos = boletos;
    }




}


